build-job:
  stage: build
  services:
    - docker:dind
  variables:
    ADDONS_DIR: /mnt/extra-addons
  script:
    - docker-compose up -d
    - docker-compose logs >> logs/compose.log
    - docker-compose down
  artifacts:
    paths:
      - logs/odoo-server.log
      - logs/compose.log