version: '3.1'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./volumes/odoo/web-data:/var/lib/odoo
      - ./volumes/odoo/conf:/etc/odoo
      - ./addons:/mnt/extra-addons
      
    environment:
      - POSTGRES_PASSWORD=postgres
  db:
    image: postgres:15
    environment:
      - Host=postgres.local
      - ports=30007
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data/pgdata